import 'package:traveller/model/search_drop_down.dart';

const List<Governorates> listGovernorates = [
  Governorates('القاهرة'),
  Governorates('الجيزة'),
  Governorates('الأسكندرية'),
  Governorates('الدقهلية'),
  Governorates('شمال سيناء'),
  Governorates('مطروح'),
  Governorates('بني سويف'),
  Governorates('الفيوم'),
  Governorates('كفر الشيخ'),
  Governorates('السويس'),
  Governorates('الإسماعيلية'),
  Governorates('دمياط'),
  Governorates('بور سعيد'),
  Governorates('الغربية'),
  Governorates('البحيرة'),
  Governorates('القليوبية'),
  Governorates('المنوفية'),
  Governorates('الشرقية'),
  Governorates('جنوب سيناء'),
  Governorates('المنيا'),
  Governorates('أسيوط'),
  Governorates('سوهاج'),
  Governorates('قنا'),
  Governorates('البحر الأحمر'),
  Governorates('الأقصر'),
  Governorates('أسوان'),
  Governorates('الواحات'),
  Governorates('الوادي الجديد'),
];

const List<Governorates> hotels = [
  Governorates('Sun Rise Hotel'),
  Governorates('Helton Hotel'),
  Governorates('Sonesta Hotel'),
  Governorates('Casio Hotel'),
  Governorates('Four Stars Hotel'),
  Governorates('Elmasa Hotel'),
  Governorates('Grand Night Hotel'),
];
